apiVersion: v1
kind: Pod
metadata:
  labels:
    rpmbuild: redis
spec:
  containers:
  - name: centos9
    image: quay.io/centos/centos:stream9
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    command:
    - sleep
    args:
    - 99d