apiVersion: v1
kind: Pod
metadata:
  labels:
    rpmbuild: redis
spec:
  securityContext:
    runAsUser: root # default UID of jenkins user in agent image
  containers:
  - name: centos7
    image: centos:7
    command:
    - sleep
    args:
    - 99d
    tty: true
  - name: centos8
    image: centos:8
    command:
    - sleep
    args:
    - 99d