apiVersion: v1
kind: Pod
metadata:
  labels:
    rpmbuild: redis
spec:
  containers:
  - name: centos7
    image: centos:7
    command:
    - sleep
    args:
    - 99d
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
  - name: centos8
    image: centos:8
    command:
    - sleep
    args:
    - 99d
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0